import os
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

def create_investor_pitch():
    doc = Document()
    
    # Title
    title = doc.add_heading('Firma-KI: Enterprise AI Security & Optimization Gateway', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Subtitle
    subtitle = doc.add_paragraph('Empowering Enterprises to Adopt AI Safely and Cost-Effectively')
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.italic = True
    subtitle.runs[0].font.size = Pt(14)
    
    doc.add_heading('The Problem', level=1)
    doc.add_paragraph(
        "Enterprises today are caught in a dilemma: they must leverage Large Language Models (LLMs) to remain competitive, "
        "but doing so exposes proprietary business data, trade secrets, and Personally Identifiable Information (PII) to "
        "third-party AI providers. Furthermore, the sheer volume of tokens required for Retrieval-Augmented Generation (RAG) "
        "and complex prompts results in exorbitant API costs and significant network latency."
    )
    
    doc.add_heading('Our Solution: Firma-KI', level=1)
    doc.add_paragraph(
        "Firma-KI is a drop-in 'Semantic Firewall' and API Gateway for enterprise AI operations. "
        "Sitting seamlessly between internal applications and external AI providers (like OpenAI, Anthropic, or Azure), "
        "our platform intercepts, cleanses, compresses, and audits every outbound text token."
    )
    
    doc.add_heading('Core Value Pillars', level=2)
    
    # Pillar 1
    p1 = doc.add_paragraph(style='List Bullet')
    r1 = p1.add_run("Absolute Data Privacy (PII Masking): ")
    r1.bold = True
    p1.add_run(
        "Driven by our advanced context-aware Python NLP engine (powered by Scrubadub), "
        "Firma-KI automatically identifies entities like names, emails, financials, and phone numbers in outbound prompts. "
        "It replaces them with synthetic placeholder tokens (e.g., [NAME_12]) before they leave your network. When the AI returns "
        "an answer, Firma-KI re-injects the original data securely, meaning the AI provider never sees your sensitive data."
    )
    
    # Pillar 2
    p2 = doc.add_paragraph(style='List Bullet')
    r2 = p2.add_run("Massive Cost Reduction (NEX Compression): ")
    r2.bold = True
    p2.add_run(
        "Using our proprietary Natural Exponential eXchange (NEX) tokenizer format, Firma-KI compresses verbose JSON payloads "
        "and English instructions into dense bitwise representations. This slashes LLM token consumption by up to 40%, directly "
        "cutting your monthly AI provider bills."
    )

    # Pillar 3
    p3 = doc.add_paragraph(style='List Bullet')
    r3 = p3.add_run("Zero-Friction Deployment: ")
    r3.bold = True
    p3.add_run(
        "Firma-KI acts as a standard OpenAI-compatible proxy. Developers only need to change their API Base URL to point to Firma-KI; "
        "no rewriting of legacy code needed. It provides a visual dashboard for compliance officers to track all usage, latency, and costs "
        "in real-time."
    )
    
    doc.add_heading('Return on Investment (ROI)', level=1)
    doc.add_paragraph(
        "By deploying Firma-KI, organizations completely neutralize the risk of AI-driven regulatory breaches (GDPR/CCPA compliant). "
        "Furthermore, the cost savings generated by our NEX pipeline typically pay for the Firma-KI license within the first three months of operation. "
        "You get the intelligence of the public cloud with the security of an on-premise airgap."
    )
    
    doc.save('FirmaKI_Investor_Pitch.docx')
    print("Created FirmaKI_Investor_Pitch.docx")

def create_technical_docs():
    doc = Document()
    
    title = doc.add_heading('Firma-KI Technical Architecture & Documentation', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_heading('1. System Overview', level=1)
    doc.add_paragraph(
        "Firma-KI is built on a scalable Django backend utilizing Python and SQLite/PostgreSQL. It serves primarily as a reverse proxy "
        "API Gateway via Django Rest Framework, acting as an intermediary for external AI provider requests. The system features "
        "a modular architecture segmented into three primary engines: the PII Masker, the NEX Token Pipeline, and the Analytics Hub."
    )
    
    doc.add_heading('2. The PII Masking Engine', level=1)
    doc.add_paragraph(
        "The PII Gateway is executed synchronously during an outbound request. It operates on two layers:"
    )
    doc.add_paragraph(
        "1. Heuristic & Regex Rules: Utilized for rigidly formatted entities such as Social Security Numbers, phone numbers, and IBANs.",
        style='List Number'
    )
    doc.add_paragraph(
        "2. Natural Language Processing (NLP): Powered by Scrubadub and TextBlob corpora. "
        "Instead of broad regex matching that incorrectly masks phrases like 'Software Engineer' or 'Sustainability Dimensions', "
        "the engine analyzes the part-of-speech context of the text to accurately isolate human names (e.g., 'John Doe').",
        style='List Number'
    )
    
    doc.add_heading('2.1 Two-Way Token Injection', level=2)
    doc.add_paragraph(
        "When an entity is masked (e.g., 'Navid Falah' to '[NAME_14]'), a temporary state lookup (DocumentKeyMapping) is persisted in the database. "
        "The proxy translates the outbound prompt. Upon receiving the LLM's response, the proxy performs a reverse regular expression sweep to "
        "re-integrate 'Navid Falah' seamlessly back into the payload, effectively shielding the data without the downstream application noticing."
    )

    doc.add_heading('2.2 Full PDF Visual Redaction', level=2)
    doc.add_paragraph(
        "Beyond unstructured text, Firma-KI uses PyMuPDF (fitz) to natively interact with binary PDF documents uploaded via the Clean Files dashboard. "
        "Masked coordinates are calculated mathematically, and black SVG overlay boxes are drawn directly onto the PDF buffer. This preserves the "
        "authentic file structure rather than flattening it to plaintext."
    )
    
    doc.add_heading('3. The 3-Stage NEX Pipeline', level=1)
    doc.add_paragraph(
        "The NEX (Natural Exponential eXchange) Pipeline is an advanced compression tool designed to minimize LLM token counts:"
    )
    doc.add_paragraph(
        "- Stage 1 (compress_to_nex): Outbound prompts are lexically parsed and compacted into NEX representations.", 
        style='List Bullet'
    )
    doc.add_paragraph(
        "- Stage 2 (LLM Transport): The compressed payload is sent to an external provider saving up to 40% on token transport costs.", 
        style='List Bullet'
    )
    doc.add_paragraph(
        "- Stage 3 (translate_from_nex): The raw response bitstream is decoded back into human-readable text before being returned to the end-user.", 
        style='List Bullet'
    )
    
    doc.add_heading('4. The Dashboard & Analytics Hub', level=1)
    doc.add_paragraph(
        "A responsive HTML/Tailwind frontend provides administrators with granular controls. The dashboard tracks variables such as "
        "latency (ms), upstream token response sizes, and financial costs per organization. A 'Clean Files' view allows for secure "
        "Markdown-enabled isolated chat interfaces linked dynamically to user-uploaded text and PDF documents."
    )
    
    doc.save('FirmaKI_Technical_Documentation.docx')
    print("Created FirmaKI_Technical_Documentation.docx")

if __name__ == '__main__':
    create_investor_pitch()
    create_technical_docs()
