# Generated by Django 5.2.11 on 2026-02-22 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('response_json', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_hit_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Cache Entry',
                'verbose_name_plural': 'Cache Entries',
                'ordering': ['-last_hit_at'],
                'unique_together': {('organization', 'prompt_hash')},
            },
        ),
    ]
