# Generated by Django 5.2.11 on 2026-02-22 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly display name', max_length=100)),
                ('provider_type', models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI / ChatGPT'), ('gemini', 'Google Gemini'), ('grok', 'xAI Grok'), ('anthropic', 'Anthropic Claude'), ('custom', 'Custom Provider')], default='deepseek', max_length=20)),
                ('api_base_url', models.URLField(help_text='Base URL for the AI API (e.g., https://api.openai.com/v1)', max_length=500)),
                ('api_key', models.CharField(help_text='API key for authentication', max_length=500)),
                ('model_name', models.CharField(default='', help_text='Model to use (e.g., gpt-4o, gemini-pro, deepseek-chat)', max_length=100)),
                ('output_webhook_url', models.URLField(blank=True, default='', help_text='Optional webhook URL to receive responses', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default provider for requests')),
                ('max_tokens', models.IntegerField(default=4096)),
                ('temperature', models.FloatField(default=0.7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('total_data_bytes', models.BigIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'AI Provider',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A friendly name for this key', max_length=100)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('original_payload', models.TextField(help_text='The original incoming JSON payload')),
                ('compressed_payload', models.TextField(help_text='The compressed/transpiled payload')),
                ('deepseek_response', models.TextField(help_text='Raw response from AI provider')),
                ('final_response', models.TextField(help_text='Final formatted response sent back')),
                ('tokens_original', models.IntegerField(default=0)),
                ('tokens_compressed', models.IntegerField(default=0)),
                ('tokens_response', models.IntegerField(default=0)),
                ('compression_ratio', models.FloatField(default=0.0)),
                ('cost_original', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_actual', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_saved', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.IntegerField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('data_bytes_in', models.BigIntegerField(default=0)),
                ('data_bytes_out', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('cached', 'Cached')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('ai_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dashboard.aiprovider')),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dashboard.apikey')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompressionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('builtin_language', 'Built-in Language'), ('builtin_programming', 'Built-in Programming (NEX)'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('is_system', models.BooleanField(default=False, help_text='System rule (cannot be deleted)')),
                ('language', models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='', max_length=5)),
                ('programming_language', models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('sql', 'SQL')], default='', max_length=20)),
                ('pattern', models.CharField(help_text='The verbose text pattern to match', max_length=500)),
                ('replacement', models.CharField(help_text='The compressed replacement', max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compression_rules', to='accounts.organization')),
            ],
            options={
                'ordering': ['rule_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='analysis_files/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('prompt', models.TextField(blank=True, default='Analyze the content of this file and provide a summary.', help_text='Instructions for the AI when analyzing this file')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('result', models.TextField(blank=True, help_text='AI analysis result')),
                ('error_message', models.TextField(blank=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_analyses', to='dashboard.aiprovider')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_analyses', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Analysis',
                'verbose_name_plural': 'File Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mask_names', models.BooleanField(default=True, help_text='Mask personal names')),
                ('mask_emails', models.BooleanField(default=True, help_text='Mask email addresses')),
                ('mask_ibans', models.BooleanField(default=True, help_text='Mask IBAN numbers')),
                ('mask_ips', models.BooleanField(default=True, help_text='Mask IP addresses')),
                ('mask_phone_numbers', models.BooleanField(default=True, help_text='Mask phone numbers')),
                ('mask_custom_ids', models.BooleanField(default=False, help_text='Mask internal document/order IDs detected by AI')),
                ('ai_detection_enabled', models.BooleanField(default=False, help_text='Use AI pre-scan to detect PII beyond regex (names, internal IDs, etc.)')),
                ('custom_regex_patterns', models.TextField(blank=True, help_text='Custom regex patterns for masking, one per line. Format: pattern|||replacement')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pii_config', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'PII Configuration',
                'verbose_name_plural': 'PII Configurations',
            },
        ),
    ]
