# Generated by Django 5.2.11 on 2026-02-22 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allowed_models',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of allowed model names (empty = all models)', max_length=500),
        ),
        migrations.AddField(
            model_name='apikey',
            name='daily_token_limit',
            field=models.IntegerField(default=0, help_text='Max tokens per day (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='enable_caching',
            field=models.BooleanField(default=True, help_text='Enable semantic caching for this key'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='enable_compression',
            field=models.BooleanField(default=True, help_text='Apply compression rules to requests using this key'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='enable_pii_masking',
            field=models.BooleanField(default=True, help_text='Apply PII masking to requests using this key'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='linked_provider',
            field=models.ForeignKey(blank=True, help_text='Force this key to route through a specific AI provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='dashboard.aiprovider'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='rate_limit',
            field=models.IntegerField(default=60, help_text='Max requests per minute (0 = unlimited)'),
        ),
    ]
