# Generated by Django 5.2.11 on 2026-02-22 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0002_apikey_allowed_models_apikey_daily_token_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Global system provider available to everyone'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='accounts.organization'),
        ),
    ]
