# Generated by Django 5.2.11 on 2026-02-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auditlog_source_auditlog_user_alter_auditlog_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='tokens_translated',
            field=models.IntegerField(default=0, help_text='Tokens in the final Stage 3 translation'),
        ),
    ]
