# Generated by Django 5.2.11 on 2026-02-25 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('dashboard', '0006_alter_fileanalysis_ai_provider_directory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('clean_content', models.TextField(help_text='The text of the document with placeholders inserted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masked_documents', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masked_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Masked Document',
                'verbose_name_plural': 'Masked Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentKeyMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placeholder', models.CharField(help_text='e.g., [EMAIL_1]', max_length=50)),
                ('original_value', models.CharField(max_length=500)),
                ('pii_type', models.CharField(max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_mappings', to='dashboard.maskeddocument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
