# Generated by Django 5.2.11 on 2026-02-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_maskeddocument_documentkeymapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskeddocument',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
