# Generated by Django 5.2.11 on 2026-02-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_maskeddocument_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskeddocument',
            name='redacted_file',
            field=models.FileField(blank=True, null=True, upload_to='masked_docs/%Y/%m/'),
        ),
    ]
