# Generated by Django 5.2.11 on 2026-03-14 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('dashboard', '0009_maskeddocument_redacted_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='documentkeymapping',
            name='document',
        ),
        migrations.RemoveField(
            model_name='maskeddocument',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='maskeddocument',
            name='user',
        ),
        migrations.RemoveField(
            model_name='piiconfig',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='enable_pii_masking',
        ),
        migrations.CreateModel(
            name='CascadeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='Confidence score threshold (0.0-1.0). Below this triggers escalation.')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cheap_provider', models.ForeignKey(blank=True, help_text='Fast/cheap model for initial processing (e.g., GPT-4o-mini, Llama-3)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cascade_cheap_configs', to='dashboard.aiprovider')),
                ('heavyweight_provider', models.ForeignKey(blank=True, help_text='Heavyweight model for escalation (e.g., Claude 3.5 Sonnet, GPT-4)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cascade_heavy_configs', to='dashboard.aiprovider')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cascade_config', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Cascade Routing Config',
                'verbose_name_plural': 'Cascade Routing Configs',
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='DocumentKeyMapping',
        ),
        migrations.DeleteModel(
            name='MaskedDocument',
        ),
        migrations.DeleteModel(
            name='PIIConfig',
        ),
    ]
