# Generated by Django 5.2.11 on 2026-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_chatsession_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileanalysis',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='fileanalysis',
            name='ai_provider',
        ),
        migrations.RemoveField(
            model_name='fileanalysis',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='fileanalysis',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='compressionrule',
            options={'ordering': ['-created_at'], 'verbose_name': 'File Analysis', 'verbose_name_plural': 'File Analyses'},
        ),
        migrations.AddField(
            model_name='compressionrule',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
        migrations.DeleteModel(
            name='FileAnalysis',
        ),
    ]
