# Generated by Django 5.2.11 on 2026-03-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_fileanalysis_directory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compressionrule',
            options={'ordering': ['rule_type', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='compressionrule',
            name='completed_at',
        ),
    ]
