# Generated by Django 5.2.11 on 2026-03-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_compressionrule_options_and_more'),
    ]

    operations = [
    ]
